name: Vote App Pipeline  to Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:

    SonarQubeTrigger:
        - name: SonarQube Trigger
        - runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@master

            ## Scan Code 

            - name: SonarQube Scan
              uses: kitabisa/sonarqube-action@master
              with:
                login: ${{ secrets.SONARQUBE_TOKEN }}